Author : Akash Pandey
DOMAIN : Data Science

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('heart.csv')

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
df.duplicated().sum()

1

In [7]:
x=df.iloc[:,:13]
y=df.iloc[:,-1]

In [8]:
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [9]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier 

In [12]:
lr=LogisticRegression()
dtc=DecisionTreeClassifier()

In [13]:
lr.fit(x_train,y_train)
dtc.fit(x_train,y_train)

C:\Users\akash pandey\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [14]:
y_pred1=lr.predict(x_test)
y_pred2=dtc.predict(x_test)

In [15]:
y_pred1

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64)

In [16]:
y_pred2

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [17]:
y_test

99     1
296    0
89     1
30     1
234    0
      ..
173    0
94     1
161    1
216    0
91     1
Name: target, Length: 61, dtype: int64

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [19]:
print('Accuracy of Logistic Regression',accuracy_score(y_test,y_pred1))
print('Accuracy of Decision Tree',accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9016393442622951
Accuracy of Decision Tree 0.8360655737704918


In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61



In [21]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.89      0.78      0.83        32
           1       0.79      0.90      0.84        29

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61



In [22]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [23]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [24]:
recall_score(y_test,y_pred1,average=None)

array([0.8125, 1.    ])

In [25]:
f1_score(y_test,y_pred1,average=None)

array([0.89655172, 0.90625   ])

In [26]:
precision_score(y_test, y_pred1, average='macro')

0.9142857142857144

In [27]:
recall_score(y_test, y_pred1, average='macro')

0.90625

In [28]:
f1_score(y_test, y_pred1, average='macro')

0.9014008620689655

In [29]:
precision_score(y_test, y_pred1, average='weighted')

0.9185011709601872

In [30]:
recall_score(y_test, y_pred1, average='weighted')

0.9016393442622951

In [31]:
f1_score(y_test, y_pred1, average='weighted')

0.901162379875636

In [32]:
precision_score(y_test,y_pred2,average=None)

array([0.89285714, 0.78787879])

In [33]:
recall_score(y_test,y_pred2,average=None)

array([0.78125   , 0.89655172])

In [34]:
f1_score(y_test,y_pred2,average=None)

array([0.83333333, 0.83870968])

In [35]:
precision_score(y_test, y_pred2, average='macro')

0.8403679653679654

In [36]:
recall_score(y_test, y_pred2, average='macro')

0.8389008620689655

In [37]:
f1_score(y_test, y_pred2, average='macro')

0.8360215053763441

In [38]:
precision_score(y_test, y_pred2, average='weighted')

0.8429494003264495

In [39]:
recall_score(y_test, y_pred1, average='weighted')

0.9016393442622951

In [40]:
f1_score(y_test, y_pred1, average='weighted')

0.901162379875636

THANK YOU